# Generated by Django 5.2.3 on 2025-07-01 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
                ('minutos_jugados', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='core.jugador')),
            ],
        ),
    ]
