# Generated by Django 5.2.3 on 2025-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_player_referee_stage_tournament_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
